[webservers]
web-1 ansible_host=158.160.44.249 fqdn=fhmcmuedv06thi7prra3.auto.internal
web-2 ansible_host=158.160.36.107 fqdn=fhmonala6l032h6lf59r.auto.internal

[databases]
main ansible_host=158.160.36.96 fqdn=fhmd4t6k5f2onitq0iri.auto.internal
replica ansible_host=158.160.42.96 fqdn=fhmr9l6ivuegkjcf05bt.auto.internal

[storage]
storage ansible_host=158.160.62.185 fqdn=fhm2koe6v1eqm7lk6tdu.auto.internal
